### ISSUE TITLE
Page reload not working with react-router

### ISSUE THREAD

**Issue by shabaz001** [perminder-klair/kickoff-react#1]
Page refreshes do not work with react-router for example if I navigate to `http://kickoff-react.surge.sh/about `from the application it works fine however if I refresh the page then it shows a 404.

I think this is a common issue with react-router. See [here](https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually)

**Comment by perminder-klair** [comment]
@shabaz001 you can fix it using htaccess file, check modl app. :)

**Comment by perminder-klair** [comment]
@shabaz001 try this in your .htaccess file:
`
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.html?q=$1 [L,QSA]
`

**Comment by shabaz001** [comment]
@perminder-klair  Yeah that did the trick. Thanks
